# Generated by Django 3.1.2 on 2021-04-20 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20210414_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='preguntas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pregunta', models.CharField(max_length=500)),
                ('RespuestaA', models.CharField(max_length=200)),
                ('RespuestaB', models.CharField(max_length=200)),
                ('RespuestaC', models.CharField(max_length=200)),
                ('RespuestaD', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Respuestas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Respuesta', models.IntegerField()),
                ('IdPregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.preguntas', verbose_name='pregunta')),
                ('IdUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.user', verbose_name='Usuario')),
            ],
        ),
    ]
