# Generated by Django 3.1.2 on 2021-05-11 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0004_preguntas_respuestas'),
    ]

    operations = [
        migrations.CreateModel(
            name='PregResp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=500)),
                ('Descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='RespUsu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='preguntas',
            name='RespuestaA',
        ),
        migrations.RemoveField(
            model_name='preguntas',
            name='RespuestaB',
        ),
        migrations.RemoveField(
            model_name='preguntas',
            name='RespuestaC',
        ),
        migrations.RemoveField(
            model_name='preguntas',
            name='RespuestaD',
        ),
        migrations.AddField(
            model_name='preguntas',
            name='Descripcion',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Respuestas',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='respusu',
            name='IdPregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.preguntas', verbose_name='Pregunta'),
        ),
        migrations.AddField(
            model_name='respusu',
            name='IdRespuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.respuesta', verbose_name='Respuesta'),
        ),
        migrations.AddField(
            model_name='respusu',
            name='IdUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='pregresp',
            name='IdPregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.preguntas', verbose_name='Pregunta'),
        ),
        migrations.AddField(
            model_name='pregresp',
            name='IdRespuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.respuesta', verbose_name='Respuesta'),
        ),
    ]
