# Generated by Django 3.1.2 on 2020-10-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save_q', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Editado'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Editado'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
    ]
