# Generated by Django 3.1.2 on 2021-05-12 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pregPrueba', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='IdUser',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='respuestausu',
            old_name='IdUser',
            new_name='User',
        ),
    ]
