# Generated by Django 3.1.2 on 2021-05-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pregPrueba', '0002_auto_20210512_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
