# Generated by Django 3.1.2 on 2020-10-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('geografia', models.CharField(max_length=50)),
                ('puntajeCre', models.IntegerField()),
                ('genero', models.IntegerField()),
                ('edad', models.IntegerField()),
                ('tenencia', models.IntegerField()),
                ('saldo', models.IntegerField()),
                ('numproduc', models.IntegerField()),
                ('tarCredito', models.IntegerField()),
                ('activo', models.IntegerField()),
                ('salario', models.IntegerField()),
            ],
        ),
    ]
